#scrapy
LOG_LEVEL = "INFO"
AUTOTHROTTLE_ENABLED = False
AUTOTHROTTLE_START_DELAY = 5
AUTOTHROTTLE_MAX_DELAY = 10
AUTOTHROTTLE_TARGET_CONCURRENCY = 1.0
DOWNLOAD_MAXSIZE = 8388608 # 8 MB
DOWNLOAD_WARNSIZE = 5242880 # 5 MB


#app
DOMAIN = "website.org"
START_URL = "https://www.website.org/"