#scrapy
LOG_LEVEL = "INFO"
AUTOTHROTTLE_ENABLED = False
AUTOTHROTTLE_START_DELAY = 5
AUTOTHROTTLE_MAX_DELAY = 10
AUTOTHROTTLE_TARGET_CONCURRENCY = 1.0


#app
DOMAIN = "website.org"
START_URL = "https://www.website.org/"